# version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./StudentManagement/Dockerfile
    ports:
      - "5049:80" # API của bạn sẽ truy cập được từ http://localhost:5049
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=DESKTOP-1M9Q7HG\\HTUAN;Database=StudentManagementSystem;Trusted_Connection=True;TrustServerCertificate=True;"
      ConnectionStrings__RedisConnection: "redis:6379"
      # Jwt__Key: "u7$$P!x9@Qw3#Zr8^Lm2&bT6*Vh1%Yj4!sN0"
      Jwt__Issuer: "StudentManagementSystem"
      Jwt__Audience: "StudentManagementSystem"

    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  # --- DỊCH VỤ MỚI ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Giao diện Prometheus sẽ ở http://localhost:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network
    depends_on:
      - backend

  # --- DỊCH VỤ MỚI ---
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
